### ISSUE TITLE
After the new ui the dark theme not working 

### ISSUE THREAD

**Issue by Satyajit0003** [yuvrajsinghgmx/ShopSmart#24]
After the new ui the dark theme not working because the new ui not integrated with material theme

**Comment by Amit-4186** [comment]
@yuvrajsinghgmx @Satyajit0003 Can you please assign this issue to me as I have experience in kotlin and jetpack compose. Also please add tags to this issue such as - gssoc-exp, level and hacotberfest. It would be really helpful.

**Comment by Farhan-Ahmad01** [comment]
The UI is not complementing the dark theme. I want to work on it, can you please assign it to me?

**Comment by yuvrajsinghgmx** [comment]
@Farhan-Ahmad01 Since this one is already assigned you may create a new one.

**Comment by Amit-4186** [comment]
@yuvrajsinghgmx Can I remove explicit color specifications? So that the app can be themed by material theme.
![Screenshot_20241005_154613_ShopSmart.jpg](https://github.com/user-attachments/assets/c5f07f5a-efee-40c0-a5e7-f7132dfad186)

![Screenshot_20241005_154625_ShopSmart.jpg](https://github.com/user-attachments/assets/fdc81b3b-6447-491e-a7da-66e8b2533acd)

This will work?

**Comment by yuvrajsinghgmx** [comment]
Yes go ahead  and i think you do not have the synced repo so please first sync your forked repo.

**Comment by Amit-4186** [comment]
> Yes go ahead  and i think you do not have the synced repo so please first sync your forked repo.

Ok
